version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://lyfenko:KBATYRJ2@database/database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=PnaDgS4Ly1lAR4KGX1NU9hali5G9wzTb
      - SECRET_KEY=secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - CLOUDINARY_CLOUD_NAME=deomhl2q4
      - CLOUDINARY_API_KEY=943472625595868
      - CLOUDINARY_API_SECRET=DxeJGfQOvVMCMDi0O1ynN3LEKjg
      - SENDGRID_API_KEY=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
    depends_on:
      - database
      - redis
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lyfenko
      - POSTGRES_PASSWORD=KBATYRJ2
      - POSTGRES_DB=database
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=PnaDgS4Ly1lAR4KGX1NU9hali5G9wzTb
