version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=******************
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=*****************
      - SECRET_KEY=secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - CLOUDINARY_CLOUD_NAME=*********
      - CLOUDINARY_API_KEY=************
      - CLOUDINARY_API_SECRET=********************
      - SENDGRID_API_KEY=**************************************
    depends_on:
      - database
      - redis
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=******
      - POSTGRES_PASSWORD=******
      - POSTGRES_DB=database
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=******************
